rocketmq:
  ###连接地址nameServer
  name-server: 192.168.66.6:9876;
  producer:
    group: pengbiaoone

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9092
